### ISSUE TITLE
[Bug] context.options.headers.entries is not a function

### ISSUE THREAD

**Issue by carlosvaldesweb** [manchenkoff/nuxt-auth-sanctum#198]
**Describe the bug**

I've updated to ```"nuxt-auth-sanctum": "^0.4.18"``` and i get:

```
[NUXT] [nuxt-auth-sanctum:ssr]  ERROR  Unable to load user identity from API context.options.headers.entries is not a function
[NUXT] 
[NUXT]   at onRequest (node_modules/nuxt-auth-sanctum/dist/runtime/httpFactory.js:70:52)
[NUXT]   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[NUXT]   at async callHooks (node_modules/ofetch/dist/shared/ofetch.4747642d.mjs:134:7)
[NUXT]   at async $fetchRaw2 (node_modules/ofetch/dist/shared/ofetch.4747642d.mjs:205:7)
[NUXT]   at async $fetch2 (node_modules/ofetch/dist/shared/ofetch.4747642d.mjs:304:15)
[NUXT]   at async initialIdentityLoad (node_modules/nuxt-auth-sanctum/dist/runtime/plugin.js:51:20)
[NUXT]   at async node_modules/nuxt-auth-sanctum/dist/runtime/plugin.js:77:113
[NUXT]   at async setup (virtual:nuxt:/Volumes/develop/webapp/.nuxt/plugins/server.mjs:93:116)
[NUXT]   at async Object.callAsync (node_modules/unctx/dist/index.mjs:72:16)
[NUXT]   at async applyPlugin (node_modules/nuxt/dist/app/nuxt.js:146:25)
```

This happens when we use interceptors in app.config.ts

```typescript
sanctum: {
    interceptors: {
      onRequest: (
        app: NuxtApp,
        ctx: FetchContext,
        _logger: ConsolaInstance,
      ) => {
        logger("woli");
        if (import.meta.server) {
          const headers = useRequestHeaders();
          ctx.options.headers = {
            ...ctx.options.headers,
            "X-Forwarded-For": headers["x-forwarded-for"],
          };

          if (app.$i18n?.localeProperties?.value?.code) {
            ctx.options.headers = {
              ...ctx.options.headers,
              "X-Language": app.$i18n.localeProperties.value.code,
            };
          }
        } else {
          ctx.options.headers = {
            ...ctx.options.headers,
            "X-Language": app.$i18n.localeProperties.value.code,
          };
        }

        return Promise.resolve();
      },
    },
  },
```

**Module information**

-   Version: `^0.4.18`
-   Content of your `nuxt.config.ts`:

```typescript
import cookieControlConfig from "./cookie-control.config";
import nuxtI18nConfig from "./nuxti18n.config";
// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  css: ["~/assets/css/main.css"],
  extends: ["@nuxt/ui-pro"],
  modules: [
    "@nuxt/ui",
    "@nuxt/image",
    "@nuxtjs/eslint-module",
    "@vueuse/motion/nuxt",
    // Only enable clarity to test and debug some days
    // "nuxt-clarity-analytics",
    "dayjs-nuxt",
    "nuxt-bugsnag",
    "@dargmuesli/nuxt-cookie-control",
    "nuxt-zod-i18n",
    "@nuxtjs/i18n",
    "nuxt-auth-sanctum",
    "@nuxtjs/seo",
    "@formkit/auto-animate/nuxt",
    "nuxt-gtag",
    "nuxt-easy-lightbox",
  ],
  gtag: {
    tags: ["AW-617182852", "G-K227879743"],
  },
  zodI18n: {
    localeCodesMapping: {
      "en-GB": "en",
      "es-ES": "es",
    },
  },
  i18n: nuxtI18nConfig,
  site: {
    url: process.env.NUXT_PUBLIC_FRONTEND_URL,
    name: process.env.APP_NAME,
  },
  sitemap: {
    sources: [process.env.NUXT_PUBLIC_BACKEND_URL + "/sitemaps"],
  },
  ogImage: { enabled: false },
  linkChecker: { enabled: false },
  seoExperiments: { enabled: false },
  seo: {
    automaticDefaults: false,
  },
  cookieControl: cookieControlConfig,
  sanctum: {
    baseUrl: process.env.NUXT_PUBLIC_BACKEND_URL, // Laravel API
    endpoints: {
      user: "/user",
    },
    redirect: {
      onLogin: "/dashboard",
    },
  },
  bugsnag: {
    publishRelease: true,
    config: {
      apiKey: process.env.NUXT_BUGSNAG_KEY,
      enabledReleaseStages: ["local", "production"],
      releaseStage: process.env.APP_ENV,
    },
  },
  eslint: {
    cache: false,
    exclude: [".nuxt", ".output", "node_modules"],
    lintOnStart: false,
  },
  image: {
    quality: 80,
    format: ["webp"],
  },
  runtimeConfig: {
    public: {
      backendUrl: process.env.NUXT_PUBLIC_BACKEND_URL,
      frontendUrl: process.env.NUXT_PUBLIC_FRONTEND_URL,
      appName: process.env.APP_NAME,
      appEnv: process.env.APP_ENV,
      pusherKey: process.env.NUXT_PUBLIC_PUSHER_KEY,
      ablyKey: process.env.NUXT_PUBLIC_ABLY_KEY,
      reverbKey: process.env.NUXT_PUBLIC_REVERB_KEY,
      reverbHost: process.env.NUXT_PUBLIC_REVERB_HOST,
      reverbPort: process.env.NUXT_PUBLIC_REVERB_PORT,
      reverbScheme: process.env.NUXT_PUBLIC_REVERB_SCHEME,
      languages: [
        { code: "es", name: "Español", icon: "i-flag-es-4x3" },
        { code: "en", name: "English", icon: "i-flag-us-4x3" },
      ],
    },
  },
  imports: {
    dirs: [
      "./utils",
      "./types",
      "./types/*",
      "./constants",
      "./tiptap-extensions",
    ],
  },

  ui: {
    icons: ["ph", "flag", "logos"],
  },
  devtools: {
    enabled: true,
  },
  experimental: {
    asyncContext: true,
    emitRouteChunkError: "automatic",
  },
  colorMode: {
    preference: "light",
  },
  tailwindcss: {
    viewer: false,
    // viewer: { endpoint: '/_tailwind', exportViewer: true }
  },
  routeRules: {

    "/register": { redirect: "/registro" },
    "/login": { redirect: "/iniciar-sesion" },
    "/pricing": { redirect: "/precios" },
    "/de/login": { redirect: "/en/login" },
    "/de/register": { redirect: "/en/register" },
    "/de/pricing": { redirect: "/en/pricing" },
    "/it/login": { redirect: "/en/login" },
    "/it/register": { redirect: "/en/register" },
    "/it/pricing": { redirect: "/en/pricing" },
    "/id/login": { redirect: "/en/login" },
    "/id/register": { redirect: "/en/register" },
    "/id/pricing": { redirect: "/en/pricing" },
    "/fr/login": { redirect: "/en/login" },
    "/fr/register": { redirect: "/en/register" },
    "/fr/pricing": { redirect: "/en/pricing" },
    "/nl/login": { redirect: "/en/login" },
    "/nl/register": { redirect: "/en/register" },
    "/nl/pricing": { redirect: "/en/pricing" },
  },
});
```

**Nuxt environment:**

-   Version: `^3.13.2`
-   SSR Enabled: **yes**
-   Environment: **local**

**Comment by manchenkoff** [comment]
@carlosvaldesweb please, see #195 while fix is on the way

**Comment by manchenkoff** [comment]
Docs are also updated - https://manchenkoff.gitbook.io/nuxt-auth-sanctum/usage/interceptors, after `ofetch` upgrade to `1.4.0` you should use a new syntax to assign headers via `set` instead of object spreading

```typescript
import type { FetchContext } from 'ofetch'
import type { ConsolaInstance } from 'consola'

export default defineAppConfig({
  sanctum: {
    interceptors: {
      onRequest: async (
        app: NuxtApp,
        ctx: FetchContext,
        logger: ConsolaInstance,
      ) => {
        if (import.meta.server) {
          const headers = useRequestHeaders()

          ctx
            .options
            .headers
            .set('X-Forwarded-For', headers['x-forwarded-for'])

          if (app.$i18n?.localeProperties?.value?.code) {
            ctx
              .options
              .headers
              .set('X-Language', app.$i18n.localeProperties.value.code)
          }
        }
        else {
          ctx
            .options
            .headers
            .set('X-Language', app.$i18n.localeProperties.value.code)
        }
      },

      onResponse: async (
        app: NuxtApp,
        ctx: FetchContext,
        logger: ConsolaInstance,
      ) => {
        logger.debug(`[onResponse] custom interceptor (${ctx.request})`)
      },
    },
  },
})
```
