### ISSUE TITLE
[Bug] 403 Forbidden after update package and Nuxi upgrade in plugin only in Production Vercel.

### ISSUE THREAD

**Issue by carlosvaldesweb** [manchenkoff/nuxt-auth-sanctum#216]
**Describe the bug**

When i make API call inside of plugin, i get 403 Frobidden only in production.

I've updated from    

 - "nuxt": "^3.12.1",
 - "nuxt-auth-sanctum": "^0.4.0",
 
**To:**

- "nuxt": "^3.13.2",
- "nuxt-auth-sanctum": "^0.5.0",

This only happen in Production in vercel, and after look and debug, i found that the issue is when i call endpoint in plugin:

```typescript
export default defineNuxtPlugin(async () => {
  const { products } = useProducts();
  const { limits } = useLimits();
  const route = useRoute();
  const sanctumClient = useSanctumClient();
  const { data, error } = await useAsyncData("globals", () =>
    sanctumClient("/globals"),
  );
  if (error.value) {
    if (error.value.statusCode === 503 && route.path !== "/maintenance") {
      await navigateTo("/maintenance");
    }
    if (route.path !== "/maintenance") {
      throw createError(error.value);
    }
  }
  if (data.value) {
    products.value = data.value.products;
    limits.value = data.value.limits;
    if (route.path === "/maintenance") {
      await navigateTo("/");
    }
  }
});
```

Looking in the Vercel logs i get:

<img width="531" alt="Captura de pantalla 2024-10-22 a la(s) 3 51 44 p m" src="https://github.com/user-attachments/assets/69455844-2f1f-4ef0-8cce-b323ba58ecea">

**Module information**

-   Version: `x.x.x`
-   Content of your `nuxt.config.ts`:

```typescript
import cookieControlConfig from "./cookie-control.config";
import nuxtI18nConfig from "./nuxti18n.config";
// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  css: ["~/assets/css/main.css"],
  extends: ["@nuxt/ui-pro"],
  modules: [
    "@nuxt/ui",
    "@nuxt/image",
    "@nuxtjs/eslint-module",
    "@vueuse/motion/nuxt",
    "dayjs-nuxt",
    "@dargmuesli/nuxt-cookie-control",
    "nuxt-zod-i18n",
    "@nuxtjs/i18n",
    "nuxt-auth-sanctum",
    "@nuxtjs/seo",
    "@formkit/auto-animate/nuxt",
    "nuxt-easy-lightbox",
    "@samk-dev/nuxt-vcalendar",
    // "@nuxt/scripts",
  ],
  zodI18n: {
    localeCodesMapping: {
      "en-GB": "en",
      "es-ES": "es",
    },
  },
  i18n: nuxtI18nConfig,
  site: {
    url: process.env.NUXT_PUBLIC_FRONTEND_URL,
    name: process.env.APP_NAME,
  },
  sitemap: {
    sources: [process.env.NUXT_PUBLIC_BACKEND_URL + "/sitemaps"],
  },
  ogImage: { enabled: false },
  linkChecker: { enabled: false },
  seoExperiments: { enabled: false },
  seo: {
    automaticDefaults: false,
  },
  cookieControl: cookieControlConfig,
  sanctum: {
    baseUrl: process.env.NUXT_PUBLIC_BACKEND_URL, // Laravel API
    endpoints: {
      user: "/user",
    },
    redirect: {
      onLogin: false,
    },
    logLevel: 5,
  },
  eslint: {
    cache: false,
    exclude: [".nuxt", ".output", "node_modules"],
    lintOnStart: false,
  },
  image: {
    quality: 80,
    format: ["webp"],
  },
  runtimeConfig: {
    public: {
      backendUrl: process.env.NUXT_PUBLIC_BACKEND_URL,
      frontendUrl: process.env.NUXT_PUBLIC_FRONTEND_URL,
      appName: process.env.APP_NAME,
      appEnv: process.env.APP_ENV,
      pusherKey: process.env.NUXT_PUBLIC_PUSHER_KEY,
      ablyKey: process.env.NUXT_PUBLIC_ABLY_KEY,
      reverbKey: process.env.NUXT_PUBLIC_REVERB_KEY,
      reverbHost: process.env.NUXT_PUBLIC_REVERB_HOST,
      reverbPort: process.env.NUXT_PUBLIC_REVERB_PORT,
      reverbScheme: process.env.NUXT_PUBLIC_REVERB_SCHEME,
      languages: [
        { code: "es", name: "Español", icon: "i-flag-es-4x3" },
        { code: "en", name: "English", icon: "i-flag-us-4x3" },
      ],
    },
  },
  imports: {
    dirs: [
      "./utils",
      "./types",
      "./types/*",
      "./constants",
      "./tiptap-extensions",
    ],
  },

  ui: {
    icons: ["ph", "flag", "logos"],
  },
  devtools: {
    enabled: true,
  },
  experimental: {
    asyncContext: true,
    emitRouteChunkError: "automatic",
  },
  colorMode: {
    preference: "light",
  },
  tailwindcss: {
    viewer: false,
    // viewer: { endpoint: '/_tailwind', exportViewer: true }
  },
  routeRules: {
    "/register": { redirect: "/registro" },
    "/login": { redirect: "/iniciar-sesion" },
    "/pricing": { redirect: "/precios" },
    "/de/login": { redirect: "/en/login" },
    "/de/register": { redirect: "/en/register" },
    "/de/pricing": { redirect: "/en/pricing" },
    "/it/login": { redirect: "/en/login" },
    "/it/register": { redirect: "/en/register" },
    "/it/pricing": { redirect: "/en/pricing" },
    "/id/login": { redirect: "/en/login" },
    "/id/register": { redirect: "/en/register" },
    "/id/pricing": { redirect: "/en/pricing" },
    "/fr/login": { redirect: "/en/login" },
    "/fr/register": { redirect: "/en/register" },
    "/fr/pricing": { redirect: "/en/pricing" },
    "/nl/login": { redirect: "/en/login" },
    "/nl/register": { redirect: "/en/register" },
    "/nl/pricing": { redirect: "/en/pricing" },
  },
});

```

**Nuxt environment:**

-   Version: `0.5.0`
-   SSR Enabled: **yes**
-   Environment: **production**

**Laravel environment:**

-   Version: `11`
-   Sanctum installed via Breeze: **yes**

<img width="1168" alt="Captura de pantalla 2024-10-22 a la(s) 3 55 05 p m" src="https://github.com/user-attachments/assets/adaccdcd-5132-4821-a6c0-b95bbd35941f">

**Comment by carlosvaldesweb** [comment]
I've enabled logLevel in 5 in develop domain and for some reason cloudflare is dispatching the challenge:

```
Trace: Response headers for "https://apidevelop.domain.com/v1/user" {
  'accept-ch': 'Sec-CH-UA-Bitness, Sec-CH-UA-Arch, Sec-CH-UA-Full-Version, Sec-CH-UA-Mobile, Sec-CH-UA-Model, Sec-CH-UA-Platform-Version, Sec-CH-UA-Full-Version-List, Sec-CH-UA-Platform, Sec-CH-UA, UA-Bitness, UA-Arch, UA-Full-Version, UA-Mobile, UA-Model, UA-Platform-Version, UA-Platform, UA',
  'cache-control': 'private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0',
  'cf-chl-out': 'ibeiXyeEiebHE+tEM7BQW9GdvcB+awQIhaF1J/TOCygpWi2GPJzCw2Nu7ePYUnDvwZvA9YXKDLuVskQCo93cLLr2Ff6bWxA+rOiaq9hGjKFNt77go1yOeq8j2AB4tGHWET+NF7knZgeOxiOh1K/F8w==$zo/XFySh0Uwi/JsvW1JYFw==',
  'cf-mitigated': 'challenge',
  'cf-ray': '8d6d236c9d38c9b9-IAD',
  connection: 'close',
  'content-encoding': 'br',
  'content-type': 'text/html; charset=UTF-8',
  'critical-ch': 'Sec-CH-UA-Bitness, Sec-CH-UA-Arch, Sec-CH-UA-Full-Version, Sec-CH-UA-Mobile, Sec-CH-UA-Model, Sec-CH-UA-Platform-Version, Sec-CH-UA-Full-Version-List, Sec-CH-UA-Platform, Sec-CH-UA, UA-Bitness, UA-Arch, UA-Full-Version, UA-Mobile, UA-Model, UA-Platform-Version, UA-Platform, UA',
  'cross-origin-embedder-policy': 'require-corp',
  'cross-origin-opener-policy': 'same-origin',
  'cross-origin-resource-policy': 'same-origin',
  date: 'Tue, 22 Oct 2024 23:06:31 GMT',
  expires: 'Thu, 01 Jan 1970 00:00:01 GMT',
  nel: '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}',
  'origin-agent-cluster': '?1',
  'permissions-policy': 'accelerometer=(),autoplay=(),browsing-topics=(),camera=(),clipboard-read=(),clipboard-write=(),geolocation=(),gyroscope=(),hid=(),interest-cohort=(),magnetometer=(),microphone=(),payment=(),publickey-credentials-get=(),screen-wake-lock=(),serial=(),sync-xhr=(),usb=()',
  'referrer-policy': 'same-origin',
  'report-to': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v4?s=A0ukDlkGdyAUEKBAmodPfvBZv%2Bx29y8P0FNcqpaLl9nPw7ryDiUDK1UdTDsOYA%2FiGLbBUERrId%2BICXI%2FOJ%2F5Yt1l9m67%2BULdCidA2g8QN4YOMVRzIRCSxRO40zzj1IUJEaFIOzsIab1kXP3Q"}],"group":"cf-nel","max_age":604800}',
  server: 'cloudflare',
  'transfer-encoding': 'chunked',
  vary: 'Accept-Encoding',
  'x-content-options': 'nosniff',
  'x-frame-options': 'SAMEORIGIN'
}
    at Object.log (file:///var/task/chunks/runtime.mjs:7244:42)
    at Consola._log (file:///var/task/node_modules/consola/dist/core.mjs:381:16)
    at resolveLog (file:///var/task/node_modules/consola/dist/core.mjs:349:14)
    at Consola._logFn (file:///var/task/node_modules/consola/dist/core.mjs:377:5)
    at Consola.trace (file:///var/task/node_modules/consola/dist/core.mjs:306:19)
    at onResponse (file:///var/task/chunks/build/server.mjs:9500:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async callHooks (file:///var/task/chunks/runtime.mjs:3516:7)
    at async $fetchRaw2 (file:///var/task/chunks/runtime.mjs:3681:7)
```

```
Trace: Request headers for "/globals" {
  accept: 'application/json',
  cookie: 'i18n_redirected=es; _fbp=fb.1.1729625303515.703441607976158854; _clck=1wgltir%7C2%7Cfq8%7C0%7C1756; _ga=GA1.1.457314687.1729625304; ncc_c=pspftkawsga; ncc_e=ps~pf~tk~aws~ga; _gcl_au=1.1.2041195483.1729625304.1584007714.1729625316.1729625326; remember_web_59ba36addc2b2f9401580f014c7f58ea4e30989d=eyJpdiI6IlhwaFMrR08rMm4zMTZVb1dPQVU0NlE9PSIsInZhbHVlIjoicVY0Unh2dkdBQ2lUYWxFSkV2cGY2bTBJZVlPVE1nSjlybEE5TDFjMlcxQnVlelJvSWc3em8xamFNM1d2R3JaUTZRSGhaQ3krZEg5U2lpdUg4TUFPWE1ydDlJYjhpWm91eUFjbDhMUW5FelpaYS83bXlBVXZ1VWVFUExXS3NqRU1zR0xTMy9HVWJ6cmpLK1U0ZFJzNjNGTmJuSmhkTWdsUjJRSzIrRUhFa2JZOFpORHg1Q05QZnZKbU1pZm9zdlVrS2ZWQU1JSVdPUVlBa0xGYWsxTEJzWEwyRkdoMmVubk1KZWxqTnVDRnRucz0iLCJtYWMiOiJjODNhZmFhZmU4YmEzZDA0YTI5MWMyYzM5OGI2MGYwNzI5Y2Y0MmZlYWZhYmU0YjRkZTMxM2RhYjk0Yzk1ZDdkIiwidGFnIjoiIn0%3D; _clsk=1wr5b61%7C1729637311932%7C13%7C1%7Cp.clarity.ms%2Fcollect; XSRF-TOKEN=eyJpdiI6Ikcxcmh6Nkl4di85ZFBKWWp3UWZrR0E9PSIsInZhbHVlIjoiaVJzcVl3TmdlUElxZGlHckY1YkdmUE1mUFM4MWJnaFdsTmo1bW05U0pwc0Z1ZEkxR0tRZXBvbVRzbjFENjVXNnh0SHUrdk9lVCtlRDAyanJoakYzNW1GS0NIVjhxK2FteFl0ejVyV28vcnIxdkNRUFhoeW1nY1l1YmJacjZhKzUiLCJtYWMiOiJhYjdmNjI1ZjBjNGEwZDNmMjAxNGY0Yzk1YmNkOGVmMjRhMTAyMTZiYjljZDE5OTA0YzZiYWViYzdmZWJlMzY2IiwidGFnIjoiIn0%3D; domain_session=eyJpdiI6ImJQYWkram94UUlpUzFEZnFlWHY4a1E9PSIsInZhbHVlIjoickZvTDRWcjN4RmlIU3ZYSGtSQ0pHZVRjMzczbU5SZ0J6QzJLMWNrS1E1MThhYXJBVFdsN0Vqd0RwdnpwRzc2UmpCU21Qa2JaRHMxM3FWa2RkdTdpMXpudVZFVnppZHFxREJLSFh0di9TY2huR1BZWGtJNWhYQTUvSDM0eWN3RUQiLCJtYWMiOiIzYzU3OTRjNTJhOWE2ODMxNTRiZWY1MmRiYzRhYjlkOTAxNWYwZGJmOGQwODY3N2IyYzM4NjM5Njc1MDMyZmE0IiwidGFnIjoiIn0%3D; _ga_K227879743=GS1.1.1729635566.3.1.1729637313.0.0.0; _vercel_jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJwUlllcjYxWGlsV0lnUDJjVkNBd3ZvQmsiLCJpYXQiOjE3Mjk2MzgzMzYsIm93bmVySWQiOiJ0ZWFtX0FvRUxNTklCNG9Id0lyNFF5dmlxVmVzZyIsImF1ZCI6ImRldmVsb3AucGFyYWZyYXNpc3QuY29tIiwidXNlcm5hbWUiOiJjYXJsb3N2YWxkZXN3ZWIiLCJzdWIiOiJzc28tcHJvdGVjdGlvbiJ9.dOn89kC65qHehZ3_AnhWaQIwWI3irY3C6DTqyDIIUfw; __vercel_toolbar=2',
  origin: 'https://develop.domain.com',
  'domain-language': 'es',
  referer: 'https://develop.domain.com',
  'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36',
  'x-forwarded-for': '189.142.1.224'
}
    at Object.log (file:///var/task/chunks/runtime.mjs:7244:42)
    at Consola._log (file:///var/task/node_modules/consola/dist/core.mjs:381:16)
    at resolveLog (file:///var/task/node_modules/consola/dist/core.mjs:349:14)
    at Consola._logFn (file:///var/task/node_modules/consola/dist/core.mjs:377:5)
    at Consola.trace (file:///var/task/node_modules/consola/dist/core.mjs:306:19)
    at onRequest (file:///var/task/chunks/build/server.mjs:9489:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async callHooks (file:///var/task/chunks/runtime.mjs:3516:7)
    at async $fetchRaw2 (file:///var/task/chunks/runtime.mjs:3589:7)
```

**Comment by manchenkoff** [comment]
Hey @carlosvaldesweb, according to the logs you posted, I don't see any problem on the module side since all the headers are set properly (origin, referrer, cookie with token). Usually when there is something wrong with the module we receive 401 or 419 response codes, but 403 might be proper behavior for Laravel. 
However, the response you got from the API is not a JSON but HTML, even for user request, this is why module shows warnings in the console. Most probably it might be related to incorrect Laravel configuration, please double check the middleware you use for these routes, session domain and cors settings. 
I prepared this part (cors, session domain) in the bug report template on purpose, so without those values I can't help much with solving this.

**Comment by carlosvaldesweb** [comment]
Thank you for your response. The issue must be with the module because Laravel isn't the one returning the 403 error; it's actually Cloudflare. Cloudflare is detecting either a misconfigured header or something unusual with the header itself, which is causing the block.

This has happened to me before when I tried configuring the interceptors. Right now, I have them disabled, but let me share my experience. When I added x-forwarded-for on the client side, Cloudflare triggered the challenge because it detected that headers had been modified from the client side, treating it as a potential security issue and blocking the request with a challenge. So i need to add import.meta.server to only add forwarded for on the server. I've disabled cloudflare proxy and works as expected.

```typescript
if (import.meta.server) {
  const headers = useRequestHeaders();
  ctx.options.headers.set(
    "X-Forwarded-For",
    headers["x-forwarded-for"],
  );
  if (app.$i18n?.localeProperties?.value?.code) {
    ctx.options.headers.set(
      "Parafrasist-Language",
      app.$i18n.localeProperties.value.code,
    );
  }
} else {
  ctx.options.headers.set(
    "Parafrasist-Language",
    app.$i18n.localeProperties.value.code,
  );
}
```
Have you modified any headers since the last update?

**Comment by manchenkoff** [comment]
> The issue must be with the module because Laravel isn't the one returning the 403 error; it's actually Cloudflare. Cloudflare is detecting either a misconfigured header or something unusual with the header itself, which is causing the block.

Oh, okay, I see @carlosvaldesweb, I thought it was from Laravel side. I am not sure about how Cloudflare works in this scenario, but the module does update headers on both sides - client (Accept, X-XSRF-TOKEN for secure methods) and server (Referer, Origin, Cookie, User-Agent). After recent release of `ofetch` I changed the way how headers are set, but not sure if it is causing your issue, more details here - https://github.com/manchenkoff/nuxt-auth-sanctum/pull/192

**Comment by manchenkoff** [comment]
Is there any chance to extract more details from Cloudflare about incorrect headers or behavior?

**Comment by carlosvaldesweb** [comment]
@manchenkoff Cloudflare doesn't get me a lot of info, But cloudflare is identifying as a bot:

```
{
  "action": "managed_challenge",
  "clientASNDescription": "AMAZON-AES",
  "clientAsn": "14618",
  "clientCountryName": "US",
  "clientIP": "54.197.176.41",
  "clientRequestHTTPHost": "apidevelop.mydomain.com",
  "clientRequestHTTPMethodName": "GET",
  "clientRequestHTTPProtocol": "HTTP/1.1",
  "clientRequestPath": "/v1/globals",
  "clientRequestQuery": "",
  "datetime": "2024-10-23T15:38:36Z",
  "rayName": "8d72d0a7ffb7205e",
  "ruleId": "874a3e315c344b1281ad4f00046aab6f",
  "rulesetId": "48ba18287c544bd7bdbe842a294f1ae2",
  "source": "firewallManaged",
  "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36",
  "matchIndex": 0,
  "metadata": [
    {
      "key": "ruleset_version",
      "value": "7"
    },
    {
      "key": "version",
      "value": "6"
    },
    {
      "key": "type",
      "value": "customer"
    }
  ],
  "sampleInterval": 1
}
```

Let me check if find more info.

**Comment by carlosvaldesweb** [comment]
![Captura de pantalla 2024-10-23 a la(s) 10 11 38 a m](https://github.com/user-attachments/assets/7b15e744-17f1-4540-a067-0fcb1a4124e5)

Definitively is detected as bot, because if i select allow to bots, page works.

**Comment by manchenkoff** [comment]
> ![Captura de pantalla 2024-10-23 a la(s) 10 11 38 a m](https://github.com/user-attachments/assets/7b15e744-17f1-4540-a067-0fcb1a4124e5)
> 
> Definitively is detected as bot, because if i select allow to bots, page works.

But how is it related to the module then? I do not have any control over infrastructure from the module side, it just assembles request and enriches that in server side if SSR is enabled.

**Comment by carlosvaldesweb** [comment]
@manchenkoff Thank you for your fast answer. I've updated ofetch from 1.4.0 to 1.4.1 and the issue was solved. Thank you.

**Comment by manchenkoff** [comment]
> @manchenkoff Thank you for your fast answer. I've updated ofetch from 1.4.0 to 1.4.1 and the issue was solved. Thank you. 

That's weird 😀 but good to know that it was solved by upgrading ofetch

**Comment by carlosvaldesweb** [comment]
Hello @manchenkoff, it seems it was a false positive from Cloudflare, and it stopped working. I reset my repository to its previous state and have been debugging each part of the requests, comparing how they were before and how they are now.

I noticed that you added the "user-agent" header for server requests in [#172](https://github.com/manchenkoff/nuxt-auth-sanctum/commit/fc96f347ad586b7285cc26deec0e8fc9a1dbf91b), whereas the previous version didn't have it. It seems like Cloudflare detects this as a threat.

I've removed the user-agent with an interceptor in the app.config.ts, but only on the server side, and it works correctly.
```typescript
sanctum: {
    interceptors: {
      onRequest: (app: NuxtApp, ctx: FetchContext, logger: ConsolaInstance) => {
            if (import.meta.server) {
                // Remove user-agent header
                ctx.options.headers.delete("user-agent");
            }
      }
    }
}
```

This is the headers before the cloudflare challenge happen printed with console.log:
```json
 {
  Accept: 'application/json',
  Referer: 'https://develop.domain.com',
  Origin: 'https://develop.domain.com',
  cookie: '_fbp=fb.1.1729625303515.703441607976158854; _ga=GA1.1.457314687.1729625304; ncc_c=pspftkawsga; ncc_e=ps~pf~tk~aws~ga; _gcl_au=1.1.2041195483.1729625304.1584007714.1729625316.1729625326; remember_web_59ba36addc2b2f9401580f014c7f58ea4e30989d=eyJpdiI6IlhwaFMrR08rMm4zMTZVb1dPQVU0NlE9PSIsInZhbHVlIjoicVY0Unh2dkdBQ2lUYWxFSkV2cGY2bTBJZVlPVE1nSjlybEE5TDFjMlcxQnVlelJvSWc3em8xamFNM1d2R3JaUTZRSGhaQ3krZEg5U2lpdUg4TUFPWE1ydDlJYjhpWm91eUFjbDhMUW5FelpaYS83bXlBVXZ1VWVFUExXS3NqRU1zR0xTMy9HVWJ6cmpLK1U0ZFJzNjNGTmJuSmhkTWdsUjJRSzIrRUhFa2JZOFpORHg1Q05QZnZKbU1pZm9zdlVrS2ZWQU1JSVdPUVlBa0xGYWsxTEJzWEwyRkdoMmVubk1KZWxqTnVDRnRucz0iLCJtYWMiOiJjODNhZmFhZmU4YmEzZDA0YTI5MWMyYzM5OGI2MGYwNzI5Y2Y0MmZlYWZhYmU0YjRkZTMxM2RhYjk0Yzk1ZDdkIiwidGFnIjoiIn0%3D; _vercel_jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJwUlllcjYxWGlsV0lnUDJjVkNBd3ZvQmsiLCJpYXQiOjE3Mjk2MzgzMzYsIm93bmVySWQiOiJ0ZWFtX0FvRUxNTklCNG9Id0lyNFF5dmlxVmVzZyIsImF1ZCI6ImRldmVsb3AucGFyYWZyYXNpc3QuY29tIiwidXNlcm5hbWUiOiJjYXJsb3N2YWxkZXN3ZWIiLCJzdWIiOiJzc28tcHJvdGVjdGlvbiJ9.dOn89kC65qHehZ3_AnhWaQIwWI3irY3C6DTqyDIIUfw; __vercel_toolbar=1; i18n_redirected=es; paraphrases_proccessed=2; _clck=1wgltir%7C2%7Cfqa%7C0%7C1756; _clsk=cgqdee%7C1729745414350%7C5%7C1%7Cj.clarity.ms%2Fcollect; summaries_proccessed=4; _ga_K227879743=GS1.1.1729745037.9.1.1729745793.0.0.0',
  'X-Forwarded-For': '187.189.127.160'
}
```

Headers now:

```json
HeadersList {
  cookies: null,
  [Symbol(headers map)]: Map(6) {
    'accept' => { name: 'Accept', value: 'application/json' },
    'referer' => { name: 'Referer', value: 'https://develop.domain.com' },
    'origin' => { name: 'Origin', value: 'https://develop.domain.com' },
    'cookie' => {
      name: 'Cookie',
      value: '_fbp=fb.1.1729625303515.703441607976158854; _ga=GA1.1.457314687.1729625304; ncc_c=pspftkawsga; ncc_e=ps~pf~tk~aws~ga; _gcl_au=1.1.2041195483.1729625304.1584007714.1729625316.1729625326; remember_web_59ba36addc2b2f9401580f014c7f58ea4e30989d=eyJpdiI6IlhwaFMrR08rMm4zMTZVb1dPQVU0NlE9PSIsInZhbHVlIjoicVY0Unh2dkdBQ2lUYWxFSkV2cGY2bTBJZVlPVE1nSjlybEE5TDFjMlcxQnVlelJvSWc3em8xamFNM1d2R3JaUTZRSGhaQ3krZEg5U2lpdUg4TUFPWE1ydDlJYjhpWm91eUFjbDhMUW5FelpaYS83bXlBVXZ1VWVFUExXS3NqRU1zR0xTMy9HVWJ6cmpLK1U0ZFJzNjNGTmJuSmhkTWdsUjJRSzIrRUhFa2JZOFpORHg1Q05QZnZKbU1pZm9zdlVrS2ZWQU1JSVdPUVlBa0xGYWsxTEJzWEwyRkdoMmVubk1KZWxqTnVDRnRucz0iLCJtYWMiOiJjODNhZmFhZmU4YmEzZDA0YTI5MWMyYzM5OGI2MGYwNzI5Y2Y0MmZlYWZhYmU0YjRkZTMxM2RhYjk0Yzk1ZDdkIiwidGFnIjoiIn0%3D; _vercel_jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJwUlllcjYxWGlsV0lnUDJjVkNBd3ZvQmsiLCJpYXQiOjE3Mjk2MzgzMzYsIm93bmVySWQiOiJ0ZWFtX0FvRUxNTklCNG9Id0lyNFF5dmlxVmVzZyIsImF1ZCI6ImRldmVsb3AucGFyYWZyYXNpc3QuY29tIiwidXNlcm5hbWUiOiJjYXJsb3N2YWxkZXN3ZWIiLCJzdWIiOiJzc28tcHJvdGVjdGlvbiJ9.dOn89kC65qHehZ3_AnhWaQIwWI3irY3C6DTqyDIIUfw; __vercel_toolbar=1; i18n_redirected=es; paraphrases_proccessed=2; _clck=1wgltir%7C2%7Cfqa%7C0%7C1756; _clsk=cgqdee%7C1729745414350%7C5%7C1%7Cj.clarity.ms%2Fcollect; summaries_proccessed=4; _ga_K227879743=GS1.1.1729745037.9.1.1729746536.0.0.0'
    },
    'user-agent' => {
      name: 'User-Agent',
      value: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36'
    },
    'x-forwarded-for' => { name: 'X-Forwarded-For', value: '187.189.127.160' }
  },
  [Symbol(headers map sorted)]: null
}
``` 

What was the reason for adding the user-agent on the server?

**Comment by manchenkoff** [comment]
> What was the reason for adding the user-agent on the server?

Because Laravel keeps regenerating session if the user agent is not the same, so the hash of the session would be different w/o it. You actually created an issue for that - https://github.com/manchenkoff/nuxt-auth-sanctum/issues/163 😄

**Comment by carlosvaldesweb** [comment]
Yes i remember the issue 😅.

Looking in the web I can't find anywhere that says that the session depends on the User Agent. I don't think it's necessary to go through SSR. But I also don't understand why cloudflare is detecting it as if it were a dangerous request when it is present, maybe we need some other header that we are forgetting when User Agent is present?

**Comment by manchenkoff** [comment]
> Looking in the web I can't find anywhere that says that the session depends on the User Agent.

I also couldn't find it in search, but discovered that in the Laravel source code. When a user agent is missing it indeed generates a different hash for CSR/SSR requests.

> But I also don't understand why cloudflare is detecting it as if it were a dangerous request when it is present, maybe we need some other header that we are forgetting when User Agent is present?

This unfortunately I do not know, but I will try to do some research on the weekend, maybe there is a workaround or smth.

At least now we have a clue 😄
