### ISSUE TITLE
[Bug] When using https and the user is authenticated when refresh it gets log out

### ISSUE THREAD

**Issue by ezekel** [manchenkoff/nuxt-auth-sanctum#275]
Hi @manchenkoff,

I noticed an issue when using HTTPS with both Laravel and Nuxt, and setting `ssr: true` in my nuxt.config. After authenticating, if I refresh the Nuxt app, it redirects me to the login page. Additionally, if I try to directly access the URL `https://larabells.local/dashboard` in the browser, it also redirects me to the login page.

### Note:

 **Disabling the ssr works fine** 
 
 
 I am using frankenphp laravell 11 and nuxt3 and caddy and docker
 
 
 .env

 `NUXT_PUBLIC_SANCTUM_BASE_URL=https://api.larabells.local`
 
 nuxt.config.ts
 
 ```
 // https://nuxt.com/docs/api/configuration/nuxt-config

export default defineNuxtConfig({

    compatibilityDate: '2024-04-03',
    devtools: {enabled: true},
    ssr: true,
    devServer: {
        host: 'larabells.local',
        port: 4000,
        //https:true

    },
     // vite: {
     //     server: {
     //        hmr: {
     //             protocol: 'wss',
     //             clientPort: 443,
     //         },
     //    },
     // },
    modules: [
        "@nuxtjs/tailwindcss",
        "shadcn-nuxt",
        '@nuxtjs/tailwindcss',
        '@nuxtjs/color-mode',
        "nuxt-auth-sanctum"
    ],
    colorMode: {
        classSuffix: ''
    },
    shadcn: {
        /**
         * Prefix for all the imported component
         */
        prefix: '',
        /**
         * Directory that the component lives in.
         * @default "./components/ui"
         */
        componentDir: './components/ui'
    },
    sanctum: {
        baseUrl:  process.env.NUXT_PUBLIC_API_URL, // Laravel API
        mode: 'cookie',

        /*endpoints: {
            user: '/api/user',
        },*/
        redirect: {
            onGuestOnly: '/dashboard',
            onLogin:'/dashboard',
            onLogout: '/login',
        },
    },
})
```
 
 
 login.vue
 
 ```
 <script setup lang="ts">
definePageMeta({
  /*layout: 'minimal',*/
  middleware: ['sanctum:guest'],
})


</script>

<template>
  <AuthLoginForm />
</template>

<style scoped>

</style>
```

dashboard.vue

```
<script setup lang="ts">
import { Button } from '~/components/ui/button'


definePageMeta({
  layout: 'auth',
  middleware: ['sanctum:auth','sanctum-verified'],
})

  <Button type="submit" class="mt-5" @click="books">
    Books
  </Button>
  
```
 
see my video

 

https://github.com/user-attachments/assets/c25147cb-15c7-4a69-b274-975082ce90e2

Thank you in advance

**Comment by manchenkoff** [comment]
Hey @ezekel, do you have different URL for Laravel which is accessible by your Nuxt server app? 

Usually it happens if SSR and CSR call different URLs and thus cookies are not available. For more details, you can also change the sanctum module log level to 5 (you can find it in the module docs) and attach output here, it should show why your user gets unauthenticated on page refresh.

**Comment by ezekel** [comment]
Hi @manchenkoff ,

can you show me where to edit the sanctum module to level 5 ?

> Usually it happens if SSR and CSR call different URLs and thus cookies are not available. 

but why if disable ssr it will works fine ? if I refresh it will not redirect to login page if I disable the ssr.

Thank you in advance.

**Comment by manchenkoff** [comment]
> can you show me where to edit the sanctum module to level 5 ?

Please, check this link - https://manchenkoff.gitbook.io/nuxt-auth-sanctum/advanced/logging

> but why if disable ssr it will works fine ? if I refresh it will not redirect to login page if I disable the ssr.

The difference between SSR and CSR is that your Laravel API is being called from different hosts, which can cause CORS issues and may not be supported by the Laravel app if the SSR host is not included in stateful domain list.

You can check more details here - https://manchenkoff.gitbook.io/nuxt-auth-sanctum/usage/cookie-authentication

**Comment by ezekel** [comment]
Hi @manchenkoff 

I don't know if I get the correct using logLevel


nuxt.config.ts
```
sanctum: {
        baseUrl:  process.env.NUXT_PUBLIC_API_URL, // Laravel API
        mode: 'cookie',

        endpoints: {
            user: '/api/user',
        },
        redirect: {
            onGuestOnly: '/dashboard',
            onLogin:'/dashboard',
            onLogout: '/login',
        },
        logLevel: 5,
    },
    ```
    
    here is the log of my docker node
    
    ```
    [nuxt-auth-sanctum:ssr]  ERROR  Unable to load user identity from API [GET] "https://api.larabells.local/api/user": <no response> fetch failed
2024-12-31T02:30:20.075973400Z 
2024-12-31T02:30:20.075977500Z     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2024-12-31T02:30:20.075981600Z     at async $fetch2 (node_modules/ofetch/dist/shared/ofetch.03887fc3.mjs:316:15)
2024-12-31T02:30:20.075985700Z     at async initialIdentityLoad (node_modules/nuxt-auth-sanctum/dist/runtime/plugin.js:42:20)
2024-12-31T02:30:20.075989400Z     at async setup (node_modules/nuxt-auth-sanctum/dist/runtime/plugin.js:70:119)
2024-12-31T02:30:20.076006200Z     at async Object.callAsync (node_modules/unctx/dist/index.mjs:72:16)
2024-12-31T02:30:20.076009800Z     at async applyPlugin (node_modules/nuxt/dist/app/nuxt.js:142:25)
2024-12-31T02:30:20.076012600Z     at async executePlugin (node_modules/nuxt/dist/app/nuxt.js:179:9)
2024-12-31T02:30:20.076015300Z     at async applyPlugins (node_modules/nuxt/dist/app/nuxt.js:193:5)
2024-12-31T02:30:20.076018300Z     at async createNuxtAppServer (node_modules/nuxt/dist/app/entry.js:15:7)
2024-12-31T02:30:20.076021800Z     at async default (node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:34:18)
2024-12-31T02:30:20.076024900Z 
2024-12-31T02:30:20.076027800Z   [cause]: fetch failed
2024-12-31T02:30:20.076031200Z 
2024-12-31T02:30:20.076034200Z       at node:internal/deps/undici/undici:13185:13
2024-12-31T02:30:20.076039500Z       at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2024-12-31T02:30:20.076042600Z       at async $fetchRaw2 (node_modules/ofetch/dist/shared/ofetch.03887fc3.mjs:258:26)
2024-12-31T02:30:20.076045500Z       at async $fetch2 (node_modules/ofetch/dist/shared/ofetch.03887fc3.mjs:316:15)
2024-12-31T02:30:20.076048600Z       at async initialIdentityLoad (node_modules/nuxt-auth-sanctum/dist/runtime/plugin.js:42:20)
2024-12-31T02:30:20.076052600Z       at async setup (node_modules/nuxt-auth-sanctum/dist/runtime/plugin.js:70:119)
2024-12-31T02:30:20.076055800Z       at async Object.callAsync (node_modules/unctx/dist/index.mjs:72:16)
2024-12-31T02:30:20.076059500Z       at async applyPlugin (node_modules/nuxt/dist/app/nuxt.js:142:25)
2024-12-31T02:30:20.076063900Z       at async executePlugin (node_modules/nuxt/dist/app/nuxt.js:179:9)
2024-12-31T02:30:20.076066900Z       at async applyPlugins (node_modules/nuxt/dist/app/nuxt.js:193:5)
2024-12-31T02:30:20.076069800Z 
2024-12-31T02:30:20.076072500Z     [cause]: connect ECONNREFUSED 172.18.0.4:443
2024-12-31T02:30:20.076075500Z 
2024-12-31T02:30:20.076078200Z         at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16)
2024-12-31T02:30:20.076081100Z         at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
2024-12-31T02:30:20.076136300Z 
2024-12-31T02:30:20.148382300Z 
2024-12-31T02:30:20.148408400Z [nuxt-auth-sanctum:ssr]  ERROR  Unable to load user identity from API [GET] "https://api.larabells.local/api/user": <no response> fetch failed
2024-12-31T02:30:20.148414000Z 
2024-12-31T02:30:20.148418000Z     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2024-12-31T02:30:20.148425200Z     at async $fetch2 (node_modules/ofetch/dist/shared/ofetch.03887fc3.mjs:316:15)
2024-12-31T02:30:20.148429400Z     at async initialIdentityLoad (node_modules/nuxt-auth-sanctum/dist/runtime/plugin.js:42:20)
2024-12-31T02:30:20.148431700Z     at async setup (node_modules/nuxt-auth-sanctum/dist/runtime/plugin.js:70:119)
2024-12-31T02:30:20.148446700Z     at async Object.callAsync (node_modules/unctx/dist/index.mjs:72:16)
2024-12-31T02:30:20.148451000Z     at async applyPlugin (node_modules/nuxt/dist/app/nuxt.js:142:25)
2024-12-31T02:30:20.148454700Z     at async executePlugin (node_modules/nuxt/dist/app/nuxt.js:179:9)
2024-12-31T02:30:20.148457600Z     at async applyPlugins (node_modules/nuxt/dist/app/nuxt.js:193:5)
2024-12-31T02:30:20.148460900Z     at async createNuxtAppServer (node_modules/nuxt/dist/app/entry.js:15:7)
2024-12-31T02:30:20.148464500Z     at async default (node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:34:18)
2024-12-31T02:30:20.148468500Z 
2024-12-31T02:30:20.148474100Z   [cause]: fetch failed
2024-12-31T02:30:20.148478700Z 
2024-12-31T02:30:20.148482100Z       at node:internal/deps/undici/undici:13185:13
2024-12-31T02:30:20.148486500Z       at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
2024-12-31T02:30:20.148489200Z       at async $fetchRaw2 (node_modules/ofetch/dist/shared/ofetch.03887fc3.mjs:258:26)
2024-12-31T02:30:20.148492000Z       at async $fetch2 (node_modules/ofetch/dist/shared/ofetch.03887fc3.mjs:316:15)
2024-12-31T02:30:20.148495000Z       at async initialIdentityLoad (node_modules/nuxt-auth-sanctum/dist/runtime/plugin.js:42:20)
2024-12-31T02:30:20.148497900Z       at async setup (node_modules/nuxt-auth-sanctum/dist/runtime/plugin.js:70:119)
2024-12-31T02:30:20.148502000Z       at async Object.callAsync (node_modules/unctx/dist/index.mjs:72:16)
2024-12-31T02:30:20.148505200Z       at async applyPlugin (node_modules/nuxt/dist/app/nuxt.js:142:25)
2024-12-31T02:30:20.148508100Z       at async executePlugin (node_modules/nuxt/dist/app/nuxt.js:179:9)
2024-12-31T02:30:20.148511100Z       at async applyPlugins (node_modules/nuxt/dist/app/nuxt.js:193:5)
2024-12-31T02:30:20.148514000Z 
2024-12-31T02:30:20.148516600Z     [cause]: connect ECONNREFUSED 172.18.0.4:443
2024-12-31T02:30:20.148519300Z 
2024-12-31T02:30:20.148522100Z         at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1611:16)
2024-12-31T02:30:20.148576600Z         at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)
2024-12-31T02:30:20.148582500Z 

```

**Comment by ezekel** [comment]
I saw this it looks like same problem withe me ssr enable

https://github.com/manchenkoff/nuxt-auth-sanctum/issues/209

but I tried to put this to sanctum module it doesnt work

```
    sanctum: {
        baseUrl:  process.env.NUXT_PUBLIC_API_URL, // Laravel API
        mode: 'cookie',

        endpoints: {
            user: '/api/user',
        },
        redirect: {
            onGuestOnly: '/dashboard',
            onLogin:'/dashboard',
            onLogout: '/login',
        },
        logLevel: 5,
        client: {
            initialRequest: true,
        }
    },
```

**Comment by manchenkoff** [comment]
> 2024-12-31T07:30:04.048885100Z [nuxt-auth-sanctum:ssr]  ERROR  Unable to load user identity from API [GET] "https://api.larabells.local/api/user": <no response> fetch failed

@ezekel, in your case, this is a problem. Your Laravel API is not reachable from the Nuxt SSR image, probably because your Docker container is named differently. It has nothing to do with the `initialRequest` config. If you have Laravel and Nuxt apps under the same network, you should name your Laravel container by the domain name as well, in your case - `api.larabells.local` should be fine.

> I tried also to include the api to the stateful domains but no luck `SANCTUM_STATEFUL_DOMAINS=larabells.local,api.larabells.local`

This is unnecessary because api.* domain is not for frontend callers.

**Comment by ezekel** [comment]
@manchenkoff 

This is my dockercompose actually my container name is already set by it's domain name that is my set up since before. but still no luck if I enable the `ssr:true`

```
       caddy:
        image: caddy:latest
        container_name: caddy-breeze
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp" # HTTP/3
        volumes:
            - caddy_data:/data
            - caddy_config:/config
            - ./Caddyfile:/etc/caddy/Caddyfile
        networks:
            - mynetwork
            
            
    php2:
        container_name: api.larabells.local
        networks:
            - mynetwork
            
            
       node:
        container_name: larabells.local  
        networks:
            - mynetwork
        depends_on:
            - php2    
            
            
      networks:
     mynetwork:
        name: my-network
        external: true          
```

**Comment by manchenkoff** [comment]
@ezekel I would recommend trying to ping the Laravel container from your Nuxt container to determine the problem (by opening a terminal session, for example). All of them should be in the same network and be available by image name as a host.

**Comment by ezekel** [comment]
@manchenkoff 

I exec my node container and ping my laravel

```
/app # ping api.larabells.local
PING api.larabells.local (172.18.0.3): 56 data bytes
64 bytes from 172.18.0.3: seq=0 ttl=64 time=0.044 ms
64 bytes from 172.18.0.3: seq=1 ttl=64 time=0.049 ms
64 bytes from 172.18.0.3: seq=2 ttl=64 time=0.048 ms
64 bytes from 172.18.0.3: seq=3 ttl=64 time=0.050 ms
64 bytes from 172.18.0.3: seq=4 ttl=64 time=0.048 ms
64 bytes from 172.18.0.3: seq=5 ttl=64 time=0.047 ms
64 bytes from 172.18.0.3: seq=6 ttl=64 time=0.050 ms
64 bytes from 172.18.0.3: seq=7 ttl=64 time=0.073 ms
64 bytes from 172.18.0.3: seq=8 ttl=64 time=0.049 ms
64 bytes from 172.18.0.3: seq=9 ttl=64 time=0.088 ms
64 bytes from 172.18.0.3: seq=10 ttl=64 time=0.050 ms
64 bytes from 172.18.0.3: seq=11 ttl=64 time=0.049 ms
64 bytes from 172.18.0.3: seq=12 ttl=64 time=0.087 ms
64 bytes from 172.18.0.3: seq=13 ttl=64 time=0.049 ms
64 bytes from 172.18.0.3: seq=14 ttl=64 time=0.049 ms
64 bytes from 172.18.0.3: seq=15 ttl=64 time=0.052 ms
64 bytes from 172.18.0.3: seq=16 ttl=64 time=0.051 ms
64 bytes from 172.18.0.3: seq=17 ttl=64 time=0.052 ms
64 bytes from 172.18.0.3: seq=18 ttl=64 time=0.053 ms
^C
--- api.larabells.local ping statistics ---
19 packets transmitted, 19 packets received, 0% packet loss
round-trip min/avg/max = 0.044/0.054/0.088 ms
```

**Comment by manchenkoff** [comment]
> I exec my node container and ping my laravel

I see, then the problem is different. Is it also available from Nuxt as https connection? You can try `curl https://api.larabells.local` or some existing endpoint in your API

**Comment by ezekel** [comment]
I can see my api is loading via https

![image](https://github.com/user-attachments/assets/b805268f-eb8b-474d-897a-ee1e636fb467)

**Comment by manchenkoff** [comment]
> I can see my api is loading via https

not from the browser, I meant from your Nuxt container since you have problem with SSR only

**Comment by ezekel** [comment]
> > I can see my api is loading via https
> 
> not from the browser, I meant from your Nuxt container since you have problem with SSR only
```
/app # curl -v https://api.larabells.local
* Host api.larabells.local:443 was resolved.
* IPv6: (none)
* IPv4: 172.18.0.3
*   Trying 172.18.0.3:443...
* connect to 172.18.0.3 port 443 from 172.18.0.5 port 37176 failed: Connection refused
* Failed to connect to api.larabells.local port 443 after 1 ms: Could not connect to server
* closing connection #0
curl: (7) Failed to connect to api.larabells.local port 443 after 1 ms: Could not connect to server
/app # 
```

**Comment by manchenkoff** [comment]
@ezekel now you have the reason why SSR doesn't work, apparently your container is not available under 443 port, I am not familiar with the containers you use, but I would imagine that you have some Caddy proxy for HTTPS, which is not Laravel instance. In that case you should use `api.larabells.local` as a name for the proxy instead and use a different value for Laravel container.

**Comment by ezekel** [comment]
@manchenkoff 

yes this is my caddfile

```
api.larabells.local {
	reverse_proxy api.larabells.local:8000
}
larabells.local {
    reverse_proxy larabells.local:4000
}
```

**Comment by ezekel** [comment]
I will be back I will try to fix the proxy

**Comment by manchenkoff** [comment]
So, in your case this is how Nuxt works:

- In browser: CSR -> `https://api.larabells.local` -> `localhost:443` -> `caddy-breeze:443` -> `api.larabells.local:8000`
- In Nuxt container: SSR -> `https://api.larabells.local` -> `api.larabells.local:443` (no container serving)

**Comment by ezekel** [comment]
@manchenkoff 

Actually I was not able to fix this in my local machine https with ssr enable, my question if I deploy this to the server using docker does my problem will fix since it is already live server not in local?
